# Generated by Django 2.2.15 on 2021-02-13 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicchatroom',
            old_name='user',
            new_name='users',
        ),
    ]
